apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-issuer
  namespace: openstack
spec:
  isCA: true
  secretName: ca-tls
  commonName: www.my-website.com
  issuerRef:
    name: vault-sub-issuer
    kind: Issuer
    group: cert-manager.io
