---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-example
  template:
    metadata:
      labels:
        app: app-example
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: "internal-app"
        #vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/octavia"
        #vault.hashicorp.com/service: "http://vault-cluster.vault.svc.cluster.local.:8200"
        vault.hashicorp.com/agent-configmap: 'my-configmap'
    spec:
      containers:
        - name: app
          image: 'external/busybox:latest'
          command:
          - sleep
          - 100000s
      serviceAccountName: internal-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "issuer"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{ with secret \"pki/issue/example-dot-com\" \"common_name=www.my-website.com\" }}{{ .Data.certificate }}{{ end }}"
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "http://vault-cluster.vault.svc.cluster.local.:8200"
    }
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "issuer"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"
    "template" = {
      "contents" = "{{ with secret \"pki/issue/example-dot-com\" \"common_name=www.my-website.com\" }}{{ .Data.certificate }}{{ end }}"
      "destination" = "/vault/secrets/db-creds"
    }

    "vault" = {
      "address" = "http://vault-cluster.vault.svc.cluster.local.:8200"
    }
