apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    sendAnonymousUsage =false
    InsecureSkipVerify = true
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
     [entryPoints.http.redirect]
          regex = "^http://(.*)"
          replacement = "https://$1"
          permanent = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          minVersion = "VersionTLS12"
          cipherSuites = [
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
          ]
    [ping]
    entryPoint = "http"
    [kubernetes]
    labelselector = "app=octavia-admin-api"
    [traefikLog]
      format = "json"
    [accessLog]
      format = "json"
    [accessLog.fields]
      defaultMode = "keep"
    [accessLog.fields.names]
    [accessLog.fields.headers]
      defaultMode = "keep"
    [accessLog.fields.headers.names]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-18T11:38:36Z"
  labels:
    app: traefik
    chart: traefik-4.2.19
    heritage: Tiller
    release: traefik-openstack-octavia-mgmt
  name: traefik-openstack-octavia-mgmt
  namespace: openstack
  resourceVersion: "6963541"
  selfLink: /api/v1/namespaces/openstack/configmaps/traefik-openstack-octavia-mgmt
  uid: 59520053-3c7d-43ed-b5cf-710cbe893ce5
